templateDir: /local/templates
additionalProperties:
  artifactId: test-typescript-sdk
files:
  /local/additional/client.ts:
    destinationFilename: /local/generated-sdk/client/client.ts
  /local/additional/package.json:
    destinationFilename: /local/generated-sdk/package.json
  /local/additional/tsconfig.json:
    destinationFilename: /local/generated-sdk/tsconfig.json