templateDir: /local/templates
additionalProperties:
  artifactId: kinde-typescript-sdk
files:
  /local/additional/README.md:
    destinationFilename: /local/generated-sdk/README.md
  /local/additional/package.json:
    destinationFilename: /local/generated-sdk/package.json
  /local/additional/pnpm-lock.yaml:
    destinationFilename: /local/generated-sdk/pnpm-lock.yaml
  /local/additional/tsconfig.json:
    destinationFilename: /local/generated-sdk/tsconfig.json
  /local/additional/tsconfig.cjs.json:
    destinationFilename: /local/generated-sdk/tsconfig.cjs.json
  /local/additional/jest.config.json:
    destinationFilename: /local/generated-sdk/jest.config.json
  /local/additional/sdk-version.sh:
    destinationFilename: /local/generated-sdk/sdk-version.sh

  /local/additional/lib/sdk/index.ts:
    folder: lib/sdk
    destinationFilename: /local/generated-sdk/lib/sdk/index.ts
  /local/additional/lib/sdk/environment.ts:
    folder: lib/sdk
    destinationFilename: /local/generated-sdk/lib/sdk/environment.ts
  /local/additional/lib/sdk/sdk-version.ts:
    folder: lib/sdk
    destinationFilename: /local/generated-sdk/lib/sdk/sdk-version.ts

  /local/additional/lib/sdk/oauth2-flows/index.ts:
    folder: lib/sdk/oauth2-flows
    destinationFilename: /local/generated-sdk/lib/sdk/oauth2-flows/index.ts
  /local/additional/lib/sdk/oauth2-flows/AuthorizationCode.ts:
    folder: lib/sdk/oauth2-flows
    destinationFilename: /local/generated-sdk/lib/sdk/oauth2-flows/AuthorizationCode.ts
  /local/additional/lib/sdk/oauth2-flows/AuthCodeWithPKCE.ts:
    folder: lib/sdk/oauth2-flows
    destinationFilename: /local/generated-sdk/lib/sdk/oauth2-flows/AuthCodeWithPKCE.ts
  /local/additional/lib/sdk/oauth2-flows/ClientCredentials.ts:
    folder: lib/sdk/oauth2-flows
    destinationFilename: /local/generated-sdk/lib/sdk/oauth2-flows/ClientCredentials.ts
  /local/additional/lib/sdk/oauth2-flows/types.ts:
    folder: lib/sdk/oauth2-flows
    destinationFilename: /local/generated-sdk/lib/sdk/oauth2-flows/types.ts

  /local/additional/lib/sdk/clients/index.ts:
    folder: lib/sdk/clients
    destinationFilename: /local/generated-sdk/lib/sdk/clients/index.ts
  /local/additional/lib/sdk/clients/authorization-code.ts:
    folder: lib/sdk/clients
    destinationFilename: /local/generated-sdk/lib/sdk/clients/authorization-code.ts
  /local/additional/lib/sdk/clients/client-credentials.ts:
    folder: lib/sdk/clients
    destinationFilename: /local/generated-sdk/lib/sdk/clients/client-credentials.ts
  /local/additional/lib/sdk/clients/types.ts:
    folder: lib/sdk/clients
    destinationFilename: /local/generated-sdk/lib/sdk/clients/types.ts

  /local/additional/lib/sdk/stores/index.ts:
    folder: lib/sdk/stores
    destinationFilename: /local/generated-sdk/lib/sdk/stores/index.ts
  /local/additional/lib/sdk/stores/MemoryStore.ts:
    folder: lib/sdk/stores
    destinationFilename: /local/generated-sdk/lib/sdk/stores/MemoryStore.ts
  /local/additional/lib/sdk/stores/BrowserSessionStore.ts:
    folder: lib/sdk/stores
    destinationFilename: /local/generated-sdk/lib/sdk/stores/BrowserSessionStore.ts
  /local/additional/lib/sdk/stores/types.ts:
    folder: lib/sdk/stores
    destinationFilename: /local/generated-sdk/lib/sdk/stores/types.ts

  /local/additional/lib/sdk/utilities/index.ts:
    folder: lib/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/sdk/utilities/index.ts
  /local/additional/lib/sdk/utilities/feature-flags.ts:
    folder: lib/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/sdk/utilities/feature-flags.ts
  /local/additional/lib/sdk/utilities/code-challenge.ts:
    folder: lib/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/sdk/utilities/code-challenge.ts
  /local/additional/lib/sdk/utilities/random-string.ts:
    folder: lib/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/sdk/utilities/random-string.ts
  /local/additional/lib/sdk/utilities/token-claims.ts:
    folder: lib/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/sdk/utilities/token-claims.ts
  /local/additional/lib/sdk/utilities/token-utils.ts:
    folder: lib/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/sdk/utilities/token-utils.ts
  /local/additional/lib/sdk/utilities/types.ts:
    folder: lib/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/sdk/utilities/types.ts

  /local/additional/lib/__tests__/mocks.ts:
    folder: lib/__tests__
    destinationFilename: /local/generated-sdk/lib/__tests__/mocks.ts
  /local/additional/lib/__tests__/sdk/oauth2-flows/AuthCodeWithPKCE.spec.ts:
    folder: lib/__tests__/sdk/oauth2-flows
    destinationFilename: /local/generated-sdk/lib/__tests__/sdk/oauth2-flows/AuthCodeWithPKCE.spec.ts
  /local/additional/lib/__tests__/sdk/oauth2-flows/ClientCredentials.spec.ts:
    folder: lib/__tests__/sdk/oauth2-flows
    destinationFilename: /local/generated-sdk/lib/__tests__/sdk/stores/ClientCredentials.spec.ts
  /local/additional/lib/__tests__/sdk/stores/stores.spec.ts:
    folder: lib/__tests__/sdk/stores
    destinationFilename: /local/generated-sdk/lib/__tests__/sdk/stores/stores.spec.ts
  /local/additional/lib/__tests__/sdk/stores/stores.browser.spec.ts:
    folder: lib/__tests__/sdk/stores
    destinationFilename: /local/generated-sdk/lib/__tests__/sdk/stores/stores.browser.spec.ts
  /local/additional/lib/__tests__/sdk/stores/BrowserSessionStore.browser.spec.ts:
    folder: lib/__tests__/sdk/stores
    destinationFilename: /local/generated-sdk/lib/__tests__/sdk/stores/BrowserSessionStore.browser.spec.ts
  /local/additional/lib/__tests__/sdk/utilities/feature-flags.spec.ts:
    folder: lib/__tests__/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/__tests__/sdk/utilities/feature-flags.spec.ts
  /local/additional/lib/__tests__/sdk/utilities/token-claims.spec.ts:
    folder: lib/__tests__/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/__tests__/sdk/utilities/token-claims.spec.ts
  /local/additional/lib/__tests__/sdk/utilities/token-utils.spec.ts:
    folder: lib/__tests__/sdk/utilities
    destinationFilename: /local/generated-sdk/lib/__tests__/sdk/utilities/token-utils.spec.ts
